#!/usr/bin/env python3
"""Render executed tutorial notebooks to mdBook Markdown pages.

The notebooks are the authoring format for CLI-first demos. This script keeps
the mdBook tutorial pages in sync with executed notebook outputs without
depending on nbconvert's HTML/Jinja stack.
"""

from __future__ import annotations

import base64
import html
import re
from pathlib import Path

import nbformat


REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs/src"
ASSETS = DOCS / "assets/notebook-output"
NOTEBOOKS = [
    (
        REPO / "notebooks/01_cli_quickstart.ipynb",
        DOCS / "tutorials/cli-quickstart.md",
        "../../notebooks/01_cli_quickstart.ipynb",
    ),
    (
        REPO / "notebooks/02_expression20_eval.ipynb",
        DOCS / "tutorials/expression20-eval.md",
        "../../notebooks/02_expression20_eval.ipynb",
    ),
    (
        REPO / "notebooks/03_go_diff_with_duckdb.ipynb",
        DOCS / "tutorials/go-diff-duckdb.md",
        "../../notebooks/03_go_diff_with_duckdb.ipynb",
    ),
]


def as_text(value: object) -> str:
    if isinstance(value, list):
        return "".join(str(item) for item in value)
    return str(value)


def strip_trailing_blank_lines(text: str) -> str:
    return text.rstrip() + "\n" if text.strip() else ""


def code_block(language: str, text: str) -> str:
    fence = "```"
    if "```" in text:
        fence = "````"
    return f"{fence}{language}\n{text.rstrip()}\n{fence}\n\n"


def render_markdown_cell(source: str, notebook_link: str, first_cell: bool) -> str:
    text = source.rstrip() + "\n\n"
    if first_cell and source.startswith("# "):
        lines = text.splitlines()
        lines.insert(1, "")
        lines.insert(2, f"Source notebook: [`{notebook_link}`]({notebook_link})")
        text = "\n".join(lines).rstrip() + "\n\n"
    return text


def render_code_cell(source: str) -> str:
    body = source.rstrip()
    if body.startswith("%%bash\n"):
        body = body.removeprefix("%%bash\n").rstrip()
        body = "\n".join(
            line
            for line in body.splitlines()
            if line
            not in {
                "set -euo pipefail",
                'cd "$(git rev-parse --show-toplevel)"',
            }
        )
        return code_block("bash", body)
    return ""


def render_outputs(notebook_stem: str, cell_index: int, outputs: list[dict]) -> str:
    rendered: list[str] = []
    stream_text: list[str] = []

    def flush_stream() -> None:
        if not stream_text:
            return
        text = strip_trailing_blank_lines("".join(stream_text))
        stream_text.clear()
        if text:
            rendered.append("Output:\n\n")
            rendered.append(code_block("text", text))

    for output_index, output in enumerate(outputs, start=1):
        output_type = output.get("output_type")
        if output_type == "stream":
            stream_text.append(as_text(output.get("text", "")))
            continue

        flush_stream()

        if output_type == "error":
            traceback = "\n".join(output.get("traceback", []))
            rendered.append("Error output:\n\n")
            rendered.append(code_block("text", traceback))
            continue

        data = output.get("data", {})
        if "image/png" in data:
            ASSETS.mkdir(parents=True, exist_ok=True)
            image_name = f"{notebook_stem}-cell{cell_index}-output{output_index}.png"
            image_path = ASSETS / image_name
            image_path.write_bytes(base64.b64decode(as_text(data["image/png"])))
            rendered.append("Output:\n\n")
            rendered.append(f"![Notebook output plot](../assets/notebook-output/{image_name})\n\n")
            continue

        if "text/html" in data:
            output_html = as_text(data["text/html"]).rstrip()
            output_html = re.sub(r"<style\\b[^>]*>.*?</style>", "", output_html, flags=re.DOTALL)
            rendered.append("Output:\n\n")
            rendered.append('<div class="notebook-output">\n')
            rendered.append(output_html)
            rendered.append("\n</div>\n\n")
            continue

        if "text/plain" in data:
            text = strip_trailing_blank_lines(as_text(data["text/plain"]))
            if text:
                rendered.append("Output:\n\n")
                rendered.append(code_block("text", text))
            continue

        if data:
            rendered.append("Output:\n\n")
            rendered.append(code_block("text", html.escape(str(data))))

    flush_stream()
    return "".join(rendered)


def render_notebook(notebook_path: Path, out_path: Path, notebook_link: str) -> None:
    notebook = nbformat.read(notebook_path, as_version=4)
    pieces: list[str] = [
        "<!-- Generated by scripts/render_notebooks_for_mdbook.py; edit the notebook source instead. -->\n\n"
    ]
    first_markdown = True
    notebook_stem = notebook_path.stem

    for cell_index, cell in enumerate(notebook.cells, start=1):
        if cell.cell_type == "markdown":
            pieces.append(render_markdown_cell(cell.source, notebook_link, first_markdown))
            first_markdown = False
            continue

        if cell.cell_type == "code":
            pieces.append(render_code_cell(cell.source))
            pieces.append(render_outputs(notebook_stem, cell_index, cell.get("outputs", [])))

    out_path.write_text("".join(pieces).rstrip() + "\n")


def main() -> int:
    for notebook_path, out_path, notebook_link in NOTEBOOKS:
        render_notebook(notebook_path, out_path, notebook_link)
        print(f"rendered {notebook_path.relative_to(REPO)} -> {out_path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
